# Generated by Django 5.2.11 on 2026-02-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='No Author', max_length=200),
        ),
    ]
